server:
  port: 8081
  servlet:
    context-path: /meng-fou

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maxqh_love_ang
    password: maxqhloveang
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
